config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
  }
  scope "(:locale)" do
    resources :books
    resources :reports
    devise_for :users, skip: :omniauth_callbacks, controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions",
    }
    resources :users, only: [:index, :show]
    resources :followings, only: [:create, :destroy]
    resources :comments, only: [:index, :edit, :create, :update, :destroy]
  end
  root to: "books#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :login_required
  before_action :set_comment, only: [:edit, :update, :destroy]
  before_action :check_user, only: [:update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = current_user.comments.order(created_at: "DESC").page(params[:page])
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_back(fallback_location: comments_url, notice: "Comment was successfully created.") }
        format.json { render :index, status: :created, location: @comment }
      else
        format.html { redirect_to comments_url, notice: "Failed create comment." }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.commentable, notice: "Comment was successfully updated." }
        format.json { render :index, status: :ok, location: @comment }
      else
        format.html { render :back }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_back(fallback_location: comments_url, notice: "Comment was successfully destroyed.") }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :commentable_type, :commentable_id)
    end

    def check_user
      redirect_to comments_url, notice: "Illegal request." unless current_user.id == @comment.user_id
    end
end

app/views/comments/_comments.html.slim
h2 コメント

table
  tbody
    - @comments.each do |comment|
      tr
        td = User.find(comment.user_id).name
        td = comment.created_at
        td = comment.content
        - if current_user.id == comment.user_id
          td = link_to "Edit", edit_comment_path(comment)
          td = link_to "Destroy", comment, data: { confirm: "Are you sure?" }, method: :delete
= paginate @comments

app/views/comments/_form.html.slim
= form_for comment do |f|
  - if comment.errors.any?
    #error_explanation
      h2 = "#{pluralize(comment.errors.count, "error")} prohibited this comment from being saved:"
      ul
        - comment.errors.full_messages.each do |message|
          li = message

  = f.hidden_field :commentable_type, value: comment.commentable_type
  = f.hidden_field :commentable_id, value: comment.commentable_id
  .field
    = f.label :content
    = f.text_area :content
  .actions = f.submit

app/views/comments/edit.html.slim
h1 コメント編集

== render "form", comment: @comment

= link_to "Back", "javascript:history.back()"

app/views/comments/index.html.slim
h1 コメント一覧

table
  thead
    tr
      th コメント先
      th = Comment.human_attribute_name(:content)

  tbody
    - @comments.each do |comment|
      tr
        td = link_to comment.commentable.title, comment.commentable
        td = comment.content
= paginate @comments