config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
  }
  scope "(:locale)" do
    resources :books
    resources :reports
    devise_for :users, skip: :omniauth_callbacks, controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions",
    }
    resources :users, only: [:index, :show]
    resources :followings, only: [:create, :destroy]
    resources :comments, only: [:index, :edit, :create, :update, :destroy]
  end
  root to: "books#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title BooksApp
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_pack_tag "application", "data-turbolinks-track": "reload"

  body
    p.navbar-text.pull-right
      - if user_signed_in?
        'Logged in as
        strong => current_user.email
        '|
        =<> link_to "プロフィール表示", user_path(id: current_user.id), class: "navbar-link"
        '|
        =<> link_to "プロフィール編集", edit_user_registration_path, class: "navbar-link"
        '|
        =< link_to "ログアウト", destroy_user_session_path, method: :delete, class: "navbar-link"
      - else
        =<> link_to "ユーザー登録", new_user_registration_path, class: "navbar-link"
        '|
        =< link_to "ログイン", new_user_session_path, class: "navbar-link"
    => link_to_if params[:locale] != "ja", "日本語", url_for(controller: controller.controller_name, action: controller.action_name, locale: "ja")
    '|
    =< link_to_if params[:locale] != "en", "English", url_for(controller: controller.controller_name, action: controller.action_name, locale: "en")
    p.navbar-text.pull-right
      => link_to "本一覧", books_path, class: "navbar-link"
      '|
      =<> link_to "日報一覧", reports_path, class: "navbar-link"
      '|
      =<> link_to "コメント一覧", comments_path, class: "navbar-link"
      '|
      =< link_to "ユーザ一覧", users_path, class: "navbar-link"
    - if notice
      p.alert.alert-success = notice
    - if alert
      p.alert.alert-danger = alert
    == yield